apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql-server
  labels:
    app: my-sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sql-server
  template:
    metadata:
      labels:
        app: my-sql-server
    spec:
      volumes:
        - name: sql-persistent-storage
          persistentVolumeClaim:
            claimName: sql-volumeclaim
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: sql-persistent-storage
      containers:
      - name: my-sql-server
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-password
                key: sa_password
          - name: MSSQL_PID
            value: Express
        volumeMounts:
         - name: sql-persistent-storage
           mountPath: /var/opt/mssql
      

  
